# imports
# -------
import json
import random


protein_network = ['modulator_of_gaba_a_receptor_anion_channel',
           'modulator_of_androgen_receptor',
           'modulator_of_neuronal_acetylcholine_receptor_protein_alpha_4_subunit',
           'acute_oral_toxicity_mouse_ld50_5mg_kg',
           'modulator_of_vasopressin_v1a_receptor',
           'modulator_of_phosphodiesterase_3',
           'modulator_of_herg',
           'modulator_of_gaba_a_receptor_alpha_1_beta_3_gamma_2',
           'modulator_of_serotonin_2a_5_ht2a_receptor',
           'inhibit_cyp2c9_acitivity',
           'modulator_of_alpha_1b_adrenergic_receptor',
           'disruptors_of_the_mitochondrial_membrane_potential',
           'modulator_of_cannabinoid_cb2_receptor',
           'agonist_of_the_constitutive_androstane_receptor_car_signaling_pathway',
           'cytotoxicity_in_hepg2_cells_0_hour',
           'modulator_of_endothelin_receptor_et_a',
           'substrates_of_cytochrome_p450_2c19',
           'modulator_of_tnf_alpha',
           'modulator_of_neurokinin_2_receptor',
           'aromatase_inhibitors',
           'antagonist_of_the_constitutive_androstane_receptor_car_signaling_pathway',
           'modulator_of_serotonin_1a_5_ht1a_receptor',
           'modulators_of_myocardial_damage',
           'modulator_of_serotonin_4_5_ht4_receptor',
           'modulator_of_hmg_coa_reductase',
           'inhibitors_and_substrates_of_cytochrome_p450_2c9',
           'modulator_of_glutamate_nmda_receptor',
           'modulator_of_angiotensin_converting_enzyme',
           'activators_of_cytochrome_p450_2a9',
           'induce_phospholipidosis',
           'agonist_of_the_thyroid_stimulating_hormone_receptor_tshr_signaling_pathway',
           'antagonist_of_the_estrogen_receptor_alpha_er_alpha_signaling_pathway_data_variant',
           'fish_tox_high_risk',
           'antagonist_of_the_retinoid_related_orphan_receptor_gamma_ror_gamma_signaling_pathway',
           'aquatic_tox_t_pyriformis',
           'modulator_of_sigma_opioid_receptor',
           'antagonist_of_the_thyroid_receptor_tr_signaling_pathway',
           'antagonist_of_the_estrogen_receptor_alpha_er_alpha_signaling_pathway',
           'block_oatp1b3_transporter',
           'modulator_of_neurokinin_1_receptor',
           'cytotoxicity_in_hepg2_cells_32_hour',
           'cytotoxicity_in_hepg2_cells_8_hour',
           'acute_oral_toxicity_rabbit_ld50_300mg_kg',
           'lungs_tox_acute_oral_ld50_500mg_kg',
           'modulator_of_vascular_endothelial_growth_factor_receptor_1',
           'modulator_of_muscarinic_acetylcholine_receptor_m2',
           'inhibit_cyp1a2_activity',
           'modulator_of_gaba_a_receptor_alpha_5_beta_3_gamma_2',
           'modulator_of_serotonin_2c_5_ht2c_receptor',
           'modulator_of_histamine_h2_receptor',
           'agonist_of_the_androgen_receptor_ar_signaling_pathway',
           'modulator_of_sodium_channel_protein_type_ix_alpha_subunit',
           'modulator_of_cyclooxygenase_1',
           'cytotoxicity_in_hek293_cells_32_hour',
           'cytotoxicity_in_hepg2_cells_24_hour',
           'cytotoxicity_in_hek293_cells_16_hour',
           'skin_sensitization',
           'modulator_of_endothelin_receptor_et_b',
           'modulator_of_acetylcholinesterase',
           'modulator_of_kappa_opioid_receptor',
           'agonist_of_h2ax',
           'agonist_of_the_estrogen_receptor_alpha_er_alpha_signaling_pathway',
           'modulator_of_platelet_activating_factor_receptor',
           'modulator_of_platelet_derived_growth_factor_receptor_beta',
           'modulator_of_vascular_endothelial_growth_factor_receptor_2',
           'antagonist_of_the_farnesoid_x_receptor_fxr_signaling_pathway',
           'modulator_of_muscarinic_acetylcholine_receptor_m1',
           'modulator_of_gaba_a_receptor_anion_channel_data_variant',
           'modulator_of_alpha_1a_adrenergic_receptor',
           'inhibitors_and_substrates_of_cytochrome_p450_3a4',
           'modulator_of_adenosine_a1_receptor',
           'agonist_of_the_farnesoid_x_receptor_fxr_signaling_pathway',
           'antagonist_of_the_constitutive_androstane_receptor_car_signaling_pathway_data_variant',
           'modulator_of_type_1_angiotensin_ii_receptor',
           'inhibitors_and_substrates_of_cytochrome_p450_2d6',
           'activator_the_aryl_hydrocarbon_receptor_ahr_signaling_pathway',
           'modulator_of_cannabinoid_cb1_receptor',
           'modulator_of_vascular_endothelial_growth_factor_receptor_3',
           'inhibit_cyp2c19_activity',
           'block_oatp1b1_transporter',
           'modulator_of_p2x_purinoceptor_3',
           'modulator_of_beta_3_adrenergic_receptor',
           'modulator_of_cyclooxygenase_2',
           'acute_oral_toxicity_rat_ld50_50mg_kg',
           'cytotoxicity_in_hepg2_cells_40_hour',
           'modulator_of_glutamate_receptor_ionotropic_ampa',
           'modulator_of_platelet_derived_growth_factor_receptor_alpha',
           'agonist_of_the_antioxidant_response_element_are_signaling_pathway',
           'modulator_of_melatonin_receptor_1b', 'modulator_of_adenosine_a2a_receptor',
           'mutagenicity',
           'acute_oral_toxicity_rodent_ld50_300mg_kg',
           'cytotoxicity_in_hek293_cells_8_hour',
           'modulator_of_platelet_derived_growth_factor_receptor',
           'modulator_of_mu_opioid_receptor',
           'modulator_of_peroxisome_proliferator_activated_receptor_gamma',
           'modulator_of_gaba_a_receptor_alpha_3_beta_3_gamma_2',
           'modulator_of_dopamine_d2_receptor',
           'cytotoxicity_in_hek293_cells_40_hour',
           'modulator_of_receptor_protein_tyrosine_kinase_erbb_2',
           'modulator_of_histamine_h1_receptor',
           'modulator_of_angiotensin_ii_type_2_at_2_receptor',
           'modulator_of_adenosine_a3_receptor',
           'antagonist_of_the_peroxisome_proliferator_activated_receptor_gamma_pparg_signaling_pathway',
           'modulator_of_prostanoid_ep2_receptor',
           'modulator_of_vascular_endothelial_growth_factor_receptor',
           'differential_cytotoxicity_isogenic_chicken_dt40_cell_lines',
           'eye_irritation',
           'modulator_of_serotonin_transporter',
           'acute_oral_toxicity_mouse_ld50_300mg_kg',
           'cytotoxicity_in_hek293_cells_24_hour',
           'antagonist_of_the_glucocorticoid_receptor_gr_signaling_pathway',
           'antagonist_of_the_vitamin_d_receptor_vdr_signaling_pathway',
           'cytotoxicity_in_hepg2_cells_16_hour',
           'modulator_of_beta_2_adrenergic_receptor',
           'modulator_of_glucocorticoid_receptor',
           'activators_of_the_heat_shock_response_signaling_pathway',
           'modulator_of_neuronal_acetylcholine_receptor_alpha3_beta4',
           'modulator_of_beta_1_adrenergic_receptor',
           'modulator_of_calcitonin_gene_related_peptide_type_1_receptor',
           'acute_oral_toxicity_rodent_ld50_50mg_kg',
           'modulator_of_gaba_a_receptor_alpha_2_beta_3_gamma_2',
           'modulator_of_dopamine_d1_receptor',
           'antagonist_of_the_androgen_receptor_ar_signaling_pathway_data_variant',
           'modulator_of_neuronal_acetylcholine_receptor_protein_alpha_7_subunit',
           'agonist_of_the_ap_1_signaling_pathway',
           'modulator_of_muscarinic_acetylcholine_receptor_m4',
           'carcinogenic_potency_mouse',
           'modulator_of_delta_opioid_receptor',
           'acute_oral_toxicity_rat_ld50_300mg_kg',
           'modulator_of_serotonin_3a_5_ht3a_receptor',
           'modulator_of_neuropeptide_y_receptor_type_1',
           'antagonist_of_the_farnesoid_x_receptor_fxr_signaling_pathway_data_variant',
           'modulator_of_adenosine_a2b_receptor',
           'carcinogenic_potency_singlecellcall',
           'agonist_of_the_p53_signaling_pathway',
           'modulator_of_alpha_2a_adrenergic_receptor',
           'differential_cytotoxicity_isogenic_chicken_dt40_rev3_mutant_cell_line',
           'agonist_of_the_glucocorticoid_receptor_gr_signaling_pathway',
           'modulator_of_alpha_2b_adrenergic_receptor',
           'modulator_of_dopamine_transporter',
           'inhibitors_of_hepatocyte_nuclear_factor_4_hnf4_dimerization',
           'drug_induced_liver_injury',
           'activators_of_the_human_pregnane_x_receptor_pxr_signaling_pathway',
           'endocine_disruption',
           'modulator_of_serotonin_1b_5_ht1b_receptor',
           'acute_oral_toxicity_mouse_ld50_50mg_kg',
           'modulator_of_muscarinic_acetylcholine_receptor_m5',
           'agonist_of_liver_x_receptor_alpha',
           'fish_tox_moderate_risk',
           'antagonist_of_the_retinoic_acid_receptor_rar_signaling_pathway',
           'modulator_of_neuronal_acetylcholine_receptor_alpha4_beta2',
           'differential_cytotoxicity_against_isogenic_chicken_dt40_cell_lines_with_known_dna_damage_response_pathways_rad54_ku70_mutant_cell_line',
           'modulator_of_serotonin_7_5_ht7_receptor',
           'induce_genotoxicity_in_human_embryonic_kidney_cells',
           'agonist_of_the_rxr_signaling_pathway',
           'carcinogenic_potency_salmonella_mutagenicity',
           'modulator_of_muscarinic_acetylcholine_receptor_m3',
           'modulator_of_bradykinin_b2_receptor',
           'agonist_of_liver_x_receptor_beta',
           'modulator_of_norepinephrine_transporter',
           'modulator_of_serotonin_2b_5_ht2b_receptor',
           'acute_oral_toxicity_rat_ld50_5mg_kg',
           'block_bile_salt_export_pump',
           'modulator_of_urotensin_ii_receptor',
           'acute_oral_toxicity_rodent_ld50_5mg_kg',
           'activators_of_cytochrome_p450_3a4',
           'agonist_of_the_peroxisome_proliferator_activated_receptor_gamma_pparg_signaling_pathway',
           'modulator_of_p2x_purinoceptor_7',
           'eye_corrosion',
           'modulator_of_cholecystokinin_a_receptor',
           'activator_alzheimer_s_amyloid_precursor',
           'antagonist_of_the_androgen_receptor_ar_signaling_pathway',
           'modulator_of_monoamine_oxidase_a'
]

if __name__ == '__main__':


    data = []


    for i in protein_network:

        row = {}

        row["name"] = i
        row["size"] = random.randint(300, 5000)

        connections = random.randint(1, 6)
        imports = []
        for j in range(0, connections):
            imports.append(random.choice(protein_network))

        row["imports"] = imports

        data.append(row)

    with open('protein_network.json', 'w') as outfile:
        json.dump(data, outfile)


